POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Promises Chaining",
    "author": "JavaScript Info",
    "url": "https://javascript.info/promise-chaining",
    "likes": 1000
}
